name: CI/CD Pipeline

on:
    push:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v1

            # - name: Login to GitHub Container Registry
            #   uses: docker/login-action@v1
            #   with:
            #     registry: ghcr.io
            #     username: ${{ github.repository_owner }}
            #     password: ${{ secrets.GHCR_PAT }}

            # - name: Build and push Docker image
            #   uses: docker/build-push-action@v2
            #   with:
            #     context: .
            #     push: true
            #     tags: ghcr.io/${{ github.repository_owner }}/telegram-bot:v1.0.0

              - name: Login to Docker Hub

            # - name: Login to Azure
            #   uses: azure/login@v1
            #   with:
            #     creds: ${{ secrets.AZURE_CREDENTIALS }}

            # - name: Deploy to Azure Container Instances
            #   uses: azure/aci-deploy@v1
            #   with:
            #     resource-group: MyGeneralResourceGroup
            #     name: telegram-bot
            #     image: ghcr.io/${{ github.repository_owner }}/telegram-bot:v1.0.0
            #     dns-name-label: telegram-bot
            #     location: canadaeast
            #     registry-login-server: ghcr.io
            #     registry-username: ${{ github.repository_owner }}
            #     registry-password: ${{ secrets.GHCR_PAT }}
            #     ports: 3000:3000
            #     environment-variables:
            #       BOT_API_KEY=${{ secrets.BOT_API_KEY }}
            #       STOCK_API_KEY=${{ secrets.STOCK_API_KEY }}
            #       CURRENCY_API_KEY=${{ secrets.CURRENCY_API_KEY }}
            #       MEME_PAGE_URL=${{ vars.MEME_PAGE_URL }}
            #       ANEK_PAGE_URL=${{ vars.ANEK_PAGE_URL }}
            #       ANEK_SEARCH_URL=${{ vars.ANEK_SEARCH_URL }}

            # - name: Set up Google Cloud SDK
            #   uses: google-github-actions/setup-gcloud@v0.2.1
            #   with:
            #       project_id: ${{ secrets.GCP_PROJECT_ID }}
            #       service_account_key: ${{ secrets.GCP_SA_KEY }}
            #       export_default_credentials: true

            # - name: Build and Push Docker image to Google Container Registry
            #   run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-bot:v1.0.0 .

            # - name: Deploy to Google Cloud Run
            #   uses: google-github-actions/deploy-cloudrun@v0.2.0
            #   with:
            #       service: telegram-bot
            #       image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-bot:v1.0.0
            #       region: us-central1
            #       env_vars: BOT_API_KEY=${{ secrets.BOT_API_KEY }},
            #           STOCK_API_KEY=${{ secrets.STOCK_API_KEY }},
            #           CURRENCY_API_KEY=${{ secrets.CURRENCY_API_KEY }},
            #           MEME_PAGE_URL=${{ vars.MEME_PAGE_URL }},
            #           ANEK_PAGE_URL=${{ vars.ANEK_PAGE_URL }},
            #           ANEK_SEARCH_URL=${{ vars.ANEK_SEARCH_URL }},
            #           PORT=3000
